{
  "openapi": "3.0.0",
  "info": {
    "title": "Creatio Web-Services (API)",
    "description": "Это сайт визуального представления Веб-сервисов (API) системы Creatio. Ниже описаны запросы которые на данный момент можно вызвать через данный OAS.<br/><br/> Для вызова методов системы, OAS необходимо открыть с таким же доменом как и Creatio веб-сервис которой нужно вызвать. *Пример:<a>https://crm.monopoly.su/swagger/</a> - для Продуктивной среды*.",
    "version": "1.0.0"
  },
  "servers": [
    {
      "description": "Тестовая среда Creatio Монополия",
      "url": "https://uat-appterra-01.monopoly.su/"
    },
    {
      "description": "Продуктивная среда Creatio Монополия",
      "url": "https://crm.monopoly.su/"
    },
    {
      "description": "Среда разработки Creatio Монополия",
      "url": "http://tst-appterra-02.monopoly.su/"
    }
  ],
  "tags": [
    {
      "name": "Авторизация",
      "description": "Веб-сервисы предусмотренные вендором"
    },
    {
      "name": "Вер-сервисы",
      "description": "Сторонние Веб-сервисы реализованные в системе"
    }
  ],
  "components": {
    "schemas": {
      "user": {
        "title": "Объект пользователя системы Creatio",
        "type": "object",
        "properties": {
          "UserName": {
            "type": "string",
            "description": "Логин пользователя Creatio",
            "example": "Supervisor"
          },
          "UserPassword": {
            "type": "string",
            "description": "Логин пользователя Creatio",
            "example": "Supervisor"
          }
        },
        "example": {
          "UserName": "Supervisor",
          "UserPassword": "Supervisor"
        }
      },
      "auth_answer_0": {
        "title": "Положительный ответ авторизации в системе Creatio",
        "type": "object",
        "properties": {
          "Code": {
            "type": "integer",
            "description": "Код ответа",
            "example": 0
          },
          "Message": {
            "type": "string",
            "description": "Сообщение ответа",
            "example": ""
          },
          "Exception": {
            "type": "object",
            "description": "Объект с информацией о ошибке",
            "example": null
          },
          "PasswordCahngeUrl": {
            "type": "object",
            "description": "Ссылка на изменение пароля",
            "example": null
          },
          "RedirectUrl": {
            "type": "string"
          }
        },
        "example": {
          "Code": 0,
          "Message": "",
          "Exception": null,
          "PasswordChangeUrl": null,
          "RedirectUrl": null
        }
      },
      "auth_answer_1": {
        "title": "Отрицательный ответ авторизации в системе Creatio",
        "type": "object",
        "properties": {
          "Code": {
            "type": "integer",
            "description": "Код ответа",
            "example": 1
          },
          "Message": {
            "type": "string",
            "description": "Сообщение ответа",
            "example": "Вы ввели неправильный логин или пароль. Проверьте корректность данных или обратитесь к системному администратору. Системный администратор может изменить пароль на странице пользователя."
          },
          "Exception": {
            "type": "object",
            "description": "Объект с информацией о ошибке",
            "properties": {
              "HelpLink": {
                "type": "string",
                "example": null
              },
              "InnerException": {
                "type": "string",
                "example": null
              },
              "Message": {
                "type": "string",
                "description": "Сообщение об ошибке",
                "example": "Вы ввели неправильный логин или пароль. Проверьте корректность данных или обратитесь к системному администратору. Системный администратор может изменить пароль на странице пользователя."
              },
              "StackTrace": {
                "type": "string",
                "example": "Ошибка безопасности."
              },
              "Type": {
                "type": "string",
                "description": "Код ошибки",
                "example": "System.Security.SecurityException"
              }
            }
          },
          "PasswordCahngeUrl": {
            "type": "string",
            "description": "Ссылка на изменение пароля",
            "example": null
          },
          "RedirectUrl": {
            "type": "string",
            "example": null
          }
        },
        "example": {
          "Code": 1,
          "Message": "Вы ввели неправильный логин или пароль. Проверьте корректность данных или обратитесь к системному администратору. Системный администратор может изменить пароль на странице пользователя.",
          "Exception": {
            "HelpLink": null,
            "InnerException": null,
            "Message": "Вы ввели неправильный логин или пароль. Проверьте корректность данных или обратитесь к системному администратору. Системный администратор может изменить пароль на странице пользователя.",
            "StackTrace": "",
            "Type": "System.Security.SecurityException"
          },
          "PasswordChangeUrl": null,
          "RedirectUrl": null
        }
      },
      "lead": {
        "title": "Объект для созданя Лида",
        "type": "object",
        "properties": {
          "accountShortname": {
            "type": "string",
            "description": "Название контрагента",
            "example": "ООО \"CompanyName\""
          },
          "leapTypeId": {
            "type": "string",
            "description": "GUID записи",
            "example": "171d093b-cc4d-4995-a083-e6d26c6734da"
          },
          "phone": {
            "type": "string",
            "description": "Номер телефона контрагента",
            "example": "78202251010"
          },
          "inn": {
            "type": "string",
            "description": "ИНН контрагента",
            "example": "3528080289"
          },
          "kpp": {
            "type": "string",
            "description": "КПП контрагента",
            "example": "352801001"
          },
          "utm": {
            "type": "object",
            "description": "UTM",
            "properties": {
              "source": {
                "type": "string",
                "description": "UtmSource",
                "example": "source"
              },
              "medium": {
                "type": "string",
                "description": "UtmMedium",
                "example": "medium"
              },
              "campaign": {
                "type": "string",
                "description": "UtmCampaign",
                "example": "campaign"
              },
              "content": {
                "type": "string",
                "description": "UtmContent",
                "example": "content"
              },
              "term": {
                "type": "string",
                "description": "UtmTerm",
                "example": "term"
              }
            },
            "example": {
              "source": "source",
              "medium": "medium",
              "campaign": "campaign",
              "content": "content",
              "term": "term"
            }
          }
        },
        "example": {
          "accountShortname": "ООО \"Название компании\"",
          "leadTypeId": "171d093b-cc4d-4995-a083-e6d26c6734da",
          "phone": 78202251010,
          "inn": 3528080289,
          "kpp": 352801001,
          "utm": {
            "source": "source",
            "medium": "medium",
            "campaign": "campaign",
            "content": "content",
            "term": "term"
          }
        }
      },
      "create_lead_answer": {
        "title": "Создание создание Лида",
        "type": "object",
        "properties": {
          "error": {
            "type": "string",
            "description": "Полное сообщение об ошибке (если нет то равно **null**)",
            "example": ""
          },
          "lead": {
            "type": "object",
            "description": "Объект лида",
            "properties": {
              "accountShortname": {
                "type": "string",
                "description": "Короткое название контрагента",
                "example": "ООО \"CompanyName\""
              },
              "leadStatus": {
                "type": "string",
                "description": "GUID записи",
                "example": "171d093b-cc4d-4995-a083-e6d26c6734da"
              },
              "leadTypeId": {
                "type": "string",
                "description": "GUID записи",
                "example": "171d093b-cc4d-4995-a083-e6d26c6734da"
              },
              "phone": {
                "type": "string",
                "description": "Номер телефона",
                "example": "78202251010"
              },
              "inn": {
                "type": "string",
                "description": "ИНН",
                "example": "3528080289"
              },
              "kpp": {
                "type": "string",
                "description": "КПП",
                "example": "352801001"
              }
            }
          },
          "message": {
            "type": "string",
            "description": "Короткое сообщение об ошибке (если нет то равно **null**)",
            "example": ""
          },
          "success": {
            "type": "boolean",
            "description": "Успешно ли добавление или нет",
            "example": true
          }
        }
      }
    }
  },
  "paths": {
    "/ServiceModel/AuthService.svc/Login": {
      "post": {
        "security": [],
        "tags": [
          "Авторизация"
        ],
        "summary": "Авторизация в системе Creatio.",
        "description": "Авторизация по объекту *JSON* в теле запроса по параметрам **UserName** и **UserPassword**",
        "requestBody": {
          "description": "Тело запроса для передачи объекта с данными пользователя в систему Creatio",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/user"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Ответ на попытку авторизации от системы Creatio <br/> Положительный либо отрицательный в зависимости от того, правильные были введенны данные или нет",
            "headers": {
              "Set-Cookie": {
                "description": "UserName",
                "schema": {
                  "type": "string",
                  "example": "UserName=abcde12345; Path=/;"
                }
              },
              "\u0000Set-Cookie": {
                "description": ".ASPXAUTH",
                "schema": {
                  "type": "string",
                  "example": ".ASPXAUTH=abcde12345; Path=/;"
                }
              },
              "Set-Cookie\u0000": {
                "description": "BPMCSRF",
                "schema": {
                  "type": "string",
                  "example": "BPMCSRF=abcde12345; Path=/;"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "oneOf": [
                    {
                      "$ref": "#/components/schemas/auth_answer_0"
                    },
                    {
                      "$ref": "#/components/schemas/auth_answer_1"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/0/ServiceModel/OmniCustomAuth.svc/Login": {
      "post": {
        "security": [],
        "tags": [
          "Авторизация"
        ],
        "summary": "Авторизация в системе Creatio.",
        "description": "Авторизация с целью получения Cookies для последующей аутентификации при выполнении других запросов",
        "requestBody": {
          "description": "Body для передачу данных пользователя в систему Creatio",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/user"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Ответ на попытку авторизации от системы Creatio",
            "headers": {
              "Set-Cookie[0]": {
                "schema": {
                  "type": "string",
                  "example": "UserName=abcde12345; Path=/; HttpOnly"
                }
              },
              "Set-Cookie[1]": {
                "schema": {
                  "type": "string",
                  "example": "BPMLOADER=abcde12345; Path=/; HttpOnly"
                }
              },
              "Set-Cookie[2]": {
                "schema": {
                  "type": "string",
                  "example": ".ASPXAUTH=abcde12345; Path=/; HttpOnly"
                }
              },
              "Set-Cookie[3]": {
                "schema": {
                  "type": "string",
                  "example": "BPMCSRF=abcde12345; Path=/; HttpOnly"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "oneOf": [
                    {
                      "$ref": "#/components/schemas/auth_answer_0"
                    },
                    {
                      "$ref": "#/components/schemas/auth_answer_1"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/0/rest/OmniLeadStatusService/Create": {
      "post": {
        "tags": [
          "Вер-сервисы"
        ],
        "summary": "Создание лида.",
        "description": "Создание лида в системе Creatio </br>Для выполнения необходимо передать в теле запроса *JSON* объект с данными **Лида**. И указать значения заголовков **.ASPXAUTH** и **BPMCSRF** (*если в Creatio включена CSRF защита*) в заголовках. Взять значения можно из заголовков ответа метода авторизации.",
        "parameters": [
          {
            "in": "header",
            "name": ".ASPXAUTH",
            "description": "Обязательный параметр во всех случаях. Возвращается после выполнения запроса на авторизацию, содержит токен, который сохраняется в **куках** и должен быть указан в **заголовке запроса**",
            "schema": {
              "type": "string"
            },
            "required": true
          },
          {
            "in": "header",
            "name": "BPMCSRF",
            "description": "Обязательный параметр **если** включена *CSRF* защита в системе Creatio. Возвращается после выполнения запроса на авторизацию, содержит токен, который сохраняется в **куках** и должен быть указан в **заголовке запроса**.",
            "schema": {
              "type": "string"
            },
            "required": false
          }
        ],
        "requestBody": {
          "description": "Тело запроса для передачи объекта с данными **Лида** в систему Creatio",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/lead"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Ответ на попытку авторизации от системы Creatio </br></br>В поле **leadStatus** при успешном выполнении запроса выводится Guid статуса. Возможных значений два: добавлен как дубль (*c5411e46-1157-47d4-a495-0172e70a077f*), добавлен без дубля (*01d3ad1d-18c9-48f7-9e79-c1c34ebff7c0*).</br></br>В полях **error**(*полное сообщение ошибки*) и **message**(*сокращенное сообщение ошибки*) отображается ошибка, если она есть, если лид был добавлен успешно, то в поле **success** будет значение *true* и ошибок не будет.",
            "content": {
              "application/json": {
                "schema": {
                  "oneOf": [
                    {
                      "$ref": "#/components/schemas/create_lead_answer"
                    }
                  ]
                }
              }
            }
          },
          "403": {
            "description": "Ошибка авторизации в системе Creatio </br>В теле ответа выводится html страница с ошибкой."
          }
        }
      }
    }
  }
}